#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
  CONFFILES="conf.d/90-sieve.conf \
  conf.d/90-sieve-extprograms.conf"

  for conffile in $CONFFILES ; do
    # Tell ucf that the file in /usr/share/dovecot is the latest
    # maintainer version, and let it handle how to manage the real
    # configuration file in /etc/dovecot.
    ucf --three-way --debconf-ok /usr/share/dovecot/$conffile /etc/dovecot/$conffile
    ucfr dovecot-sieve /etc/dovecot/$conffile
  done
fi


