#!/bin/sh
set -e

# Automatically added by dh_installinit
if [ -x "/etc/init.d/fail2ban" ]; then
	invoke-rc.d fail2ban stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p fail2ban 
else
	dpkg -L fail2ban | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
