/.
/usr
/usr/lib
/usr/lib/php5
/usr/lib/php5/20131226
/usr/lib/php5/20131226/pdo.so
/usr/lib/php5/20131226/opcache.so
/usr/lib/php5/sessionclean
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/php5-common
/usr/share/doc
/usr/share/doc/php5-common
/usr/share/doc/php5-common/CREDITS
/usr/share/doc/php5-common/README.Debian.security
/usr/share/doc/php5-common/copyright
/usr/share/doc/php5-common/test-results.txt.gz
/usr/share/doc/php5-common/EXTENSIONS.gz
/usr/share/doc/php5-common/CODING_STANDARDS.gz
/usr/share/doc/php5-common/README.EXT_SKEL.gz
/usr/share/doc/php5-common/README.SELF-CONTAINED-EXTENSIONS.gz
/usr/share/doc/php5-common/UPGRADING.gz
/usr/share/doc/php5-common/UPGRADING.INTERNALS.gz
/usr/share/doc/php5-common/README.Debian.gz
/usr/share/doc/php5-common/changelog.Debian.gz
/usr/share/doc/php5-common/NEWS.Debian.gz
/usr/share/doc/php5-common/changelog.gz
/usr/share/php5
/usr/share/php5/sapi
/usr/share/php5/php.ini-production
/usr/share/php5/php.ini-production.cli
/usr/share/php5/php.ini-development
/usr/share/php5/php5-helper
/usr/share/php5/php5-maintscript-helper
/usr/share/php5/common
/usr/share/php5/common/pdo.ini
/usr/share/php5/common/opcache.ini
/usr/share/bug
/usr/share/bug/php5-common
/usr/share/bug/php5-common/script
/usr/share/bug/php5-common/control
/usr/sbin
/usr/sbin/php5enmod
/usr/sbin/php5query
/etc
/etc/php5
/etc/php5/mods-available
/etc/cron.d
/etc/cron.d/php5
/var
/var/lib
/var/lib/php5
/var/lib/php5/sessions
/var/lib/php5/modules
/usr/sbin/php5dismod
