#!/bin/sh

set -e

if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
    update-alternatives --remove php /usr/bin/php5
    update-alternatives --remove phar /usr/bin/phar5
fi

php5_enable() { return 0; }

if [ -e /usr/share/php5/php5-maintscript-helper ]; then
    . /usr/share/php5/php5-maintscript-helper

    mods=$(php5query -M)
    for mod in $mods; do
	php5_invoke dismod cli $mod
    done
fi



exit 0
