#!/bin/sh

MATCH="^[[:space:]]*($|;)"

echo "==== Additional PHP 7.1 information ====" >&3
echo "" >&3
echo "++++ PHP 7.1 SAPI (php7.1query -S): ++++" >&3
/usr/sbin/php7.1query -S >&3
echo "" >&3
echo "++++ PHP 7.1 Extensions (php7.1query -M -v): ++++" >&3
/usr/sbin/php7.1query -M -v >&3
echo "" >&3

echo "++++ Configuration files: ++++" >&3
"**** /etc/php/7.1/fpm/php.ini ****" >&3
grep -Ev "$MATCH" /etc/php/7.1/fpm/php.ini >&3
echo "" >&3
find /etc/php/7.1/fpm/conf.d/ -name '*.ini' | \
while read CONF; do
    echo "**** $CONF ****" >&3
    grep -Ev "$MATCH" "$CONF" >&3
    echo "" >&3
done
